### ISSUE TITLE
Navigation buttons not working - Incorrect registry logic on Neoforge

### ISSUE THREAD

**Issue by Mansarde** [CommandrMoose/TardisRefined#292]
### Issue description

With NeoForge as mod loader, the buttons for "increment", "randomize" and the coordinates buttons (X, Y, Z) don't work.
They show their labels, but neither left- nor right-clicking produces any effect (not even the button sound).
All other buttons work just fine.

**With the Fabric version of the mod this issue does not exist.**

<details>
<summary>Error message when I right-click one of the coordinate buttons</summary>

```
[15:17:14] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundInteractPacket@7ba1dd2e, suppressing error
java.lang.IllegalStateException: Cannot create a registry that already exists - ResourceKey[minecraft:root / tardis_refined:upgrade]
	at net.neoforged.neoforge.registries.DeferredRegister.makeRegistry(DeferredRegister.java:324) ~[neoforge-20.2.86-universal.jar%23189!/:?] {re:classloading}
	at net.neoforged.neoforge.registries.DeferredRegister.makeRegistry(DeferredRegister.java:229) ~[neoforge-20.2.86-universal.jar%23189!/:?] {re:classloading}
	at whocraft.tardis_refined.registry.neoforge.DeferredRegistryImpl$Impl.getRegistry(DeferredRegistryImpl.java:76) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.tardis.manager.TardisPilotingManager.getCoordinateIncrements(TardisPilotingManager.java:785) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.tardis.manager.TardisPilotingManager.getCordIncrement(TardisPilotingManager.java:769) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.tardis.control.flight.CoordinateControl.changeCoord(CoordinateControl.java:47) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.tardis.control.flight.CoordinateControl.onRightClick(CoordinateControl.java:35) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.entity.ControlEntity.lambda$handleRightClick$3(ControlEntity.java:461) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at whocraft.tardis_refined.common.entity.ControlEntity.handleRightClick(ControlEntity.java:439) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.entity.ControlEntity.interactAt(ControlEntity.java:258) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.lambda$onInteraction$0(ServerGamePacketListenerImpl.java:1523) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.performInteraction(ServerGamePacketListenerImpl.java:1506) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.onInteraction(ServerGamePacketListenerImpl.java:1523) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAtLocationAction.dispatch(ServerboundInteractPacket.java:146) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:66) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:1500) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:53) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:13) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:23) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:788) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:160) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:771) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:765) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:109) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:751) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:686) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:248) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```
</details>

<details>
<summary>Error message when I right-click the randomize button</summary>

```
[15:19:12] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundInteractPacket@5fa93fbf, suppressing error
java.lang.IllegalStateException: Cannot create a registry that already exists - ResourceKey[minecraft:root / tardis_refined:upgrade]
	at net.neoforged.neoforge.registries.DeferredRegister.makeRegistry(DeferredRegister.java:324) ~[neoforge-20.2.86-universal.jar%23189!/:?] {re:classloading}
	at net.neoforged.neoforge.registries.DeferredRegister.makeRegistry(DeferredRegister.java:229) ~[neoforge-20.2.86-universal.jar%23189!/:?] {re:classloading}
	at whocraft.tardis_refined.registry.neoforge.DeferredRegistryImpl$Impl.getRegistry(DeferredRegistryImpl.java:76) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.tardis.manager.TardisPilotingManager.getCoordinateIncrements(TardisPilotingManager.java:785) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.tardis.manager.TardisPilotingManager.getCordIncrement(TardisPilotingManager.java:769) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.tardis.control.flight.RandomControl.onRightClick(RandomControl.java:28) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.entity.ControlEntity.lambda$handleRightClick$3(ControlEntity.java:461) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at whocraft.tardis_refined.common.entity.ControlEntity.handleRightClick(ControlEntity.java:439) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at whocraft.tardis_refined.common.entity.ControlEntity.interactAt(ControlEntity.java:258) ~[tardis_refined-1.20.2-2.0.1.jar%23183!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.lambda$onInteraction$0(ServerGamePacketListenerImpl.java:1523) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.performInteraction(ServerGamePacketListenerImpl.java:1506) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.onInteraction(ServerGamePacketListenerImpl.java:1523) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAtLocationAction.dispatch(ServerboundInteractPacket.java:146) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:66) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:1500) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:53) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:13) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:23) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:788) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:160) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:120) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:771) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:765) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:130) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:752) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:686) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:248) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis_refined-common.mixins.json:MinecraftServerStorageAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```
</details>

### Steps to reproduce

1. Enter TARDIS.
2. Right-click Y coordinate button on TARDIS console.
3. Right-click increment button on TARDIS console.
4. Right-click randomize button on TARDIS console.

The result will be that there is no reaction ingame at all.
Instead there is an error message in the log for each attempted interaction with these buttons.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Neoforge

### Mod Loader version

NeoForge Loader Version 20.2.86 (also tried with 20.2.88)

### Tardis Refined version

v2.0.1

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/Mansarde/062d81bc27a78891b7a055904919ac2d

**Comment by 50ap5ud5** [comment]
Thanks for reporting this, this is being addressed in the next version.
